### ISSUE TITLE
ADTs are broken!

### ISSUE THREAD

**Issue by ryanworsley** [sksamuel/avro4s#187]
This should work right?

```
sealed trait Foo
case class Bar(foo: Option[String]) extends Foo
case class Baz(foo: String) extends Foo

SchemaFor[Foo]()
```

On Scala 2.12.5 or 2.12.4 I'm getting the really interesting error message:

```Sealed traits/classes should be handled by coproduct generic!  SchemaFor[Foo]()```

Any ideas what could be the cause @sksamuel?

Cheers,
Ryan.

**Comment by ryanworsley** [comment]
It's also the case that `Either` seems to have the same issue...

```
case class Foo(s: String)
case class Bar(s: String)

SchemaFor[Either[Foo, Bar]]()
```

Same error as above.

**Comment by sksamuel** [comment]
It's broken in certain versions of 2.12 and I don't know why.

**Comment by ryanworsley** [comment]
Ah that's a shame, any idea of any versions that do work that I could try @sksamuel?

**Comment by ryanworsley** [comment]
Well I just did some testing @sksamuel and no versions of 2.12 work.  I also tried 2.11.12 and the same bug is present...  I could start trying older versions of avro4s if that would help you?  I've no practical experience of writing and debugging macros though.

**Comment by ryanworsley** [comment]
If I got all the way back to version 1.6.4 then I get a different error;

```Error:(8, 25) could not find Lazy implicit value of type com.sksamuel.avro4s.ToSchema[A]
  val schema = SchemaFor[Either[Foo, Bar]]()```

**Comment by sksamuel** [comment]
Must be something else then. I'll investigate.

**Comment by ryanworsley** [comment]
I'm doing a quick prototype of schema generation using pure shapeless - I'll let you know the outcome of that, could be useful to the project.

**Comment by sksamuel** [comment]
I would love to use Shapeless rather than inhouse macros. One of the issues I had in the past was getting a handle to the custom annotations used by the project so set things like scale, doc, namespace etc.

**Comment by ryanworsley** [comment]
Yeah that sounds like it could be a pain, I'll have a think and see if anything comes to mind.

**Comment by sksamuel** [comment]
Fixed in master. Will be in 1.8.4 which will be released today.

**Comment by ryanworsley** [comment]
Awesome @sksamuel - I'll go test it now (just returned from a trip).  I've head reasonable success with a Shapeless implementation that I'll share with you soon - you might want to adopt it, might not.

**Comment by ryanworsley** [comment]
I don't see a 1.8.4 over here: https://mvnrepository.com/artifact/com.sksamuel.avro4s/avro4s-core

Is there something we need to do to push it out @sksamuel?

**Comment by sksamuel** [comment]
Release was canned as the fix doesn't work on 2.11 yet.

On 11 Apr 2018 8:35 am, "ryanworsley" <notifications@github.com> wrote:

I don't see a 1.8.4 over here:
https://mvnrepository.com/artifact/com.sksamuel.avro4s/avro4s-core

Is there something we need to do to push it out @sksamuel
<https://github.com/sksamuel>?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/avro4s/issues/187#issuecomment-380356943>, or mute
the thread

**Comment by ryanworsley** [comment]
Ah right, understood - thanks!

**Comment by edrevo** [comment]
Is there any avro4s known to work with scala 2.12.x?

**Comment by sksamuel** [comment]
I've pushed out a version of avro4s for 2.11 and 2.12 which is release 1.9.0

**Comment by 2chilled** [comment]
@edrevo This works using my [fork](Should be fixed for Scala 2.12 in https://github.com/2chilled/avro4s)

**Comment by jadireddi** [comment]
@edrevo , Still getting  `Sealed traits/classes should be handled by coproduct generic!` for above example using your fork: https://github.com/2chilled/avro4s

**Comment by 2chilled** [comment]
@jadireddi You are absolutely right. I think the main problem is that avro unions (which are coproducts, actually) cannot contain other unions (see [here](http://avro.apache.org/docs/1.8.2/spec.html#Unions). This fact is problematic when traversing ADTs, as you'd have to somehow check whether your "cursor" is NOT pointing on a Scala coproduct type... The workaround for the moment is simple: Just wrap your coproduct into a one factor product, e.g. `final case class FooWrapper(foo: Foo)` and it will work. At $WORK we use this workaround on a really big ADT together with my fork and everything is fine.

**Comment by jadireddi** [comment]
@2chilled , Even without your fix, by wrapping eg:  `final case class FooWrapper(foo: Foo` in avro4s `1.9.0` works.

**Comment by 2chilled** [comment]
That's good news but I guess it stops working when you start nesting your types within (companion) objects. Also, object namespacing is not reflected in Avro schema which can lead to name conflicts unless you pimp your identifiers for disambiguation.
