### ISSUE TITLE
Schema generated is not always the same

### ISSUE THREAD

**Issue by davideicardi** [sksamuel/avro4s#260]
It is possible that when calling `AvroSchema` macro the schema is not generated always in the same way?

Inside my code I have a call like:
```
SchemaNormalization.parsingFingerprint64(AvroSchema[MyCaseClass])
```

Mostly of the time the fingerprint returns me a specific value, but sometime (unfortunately I have not yet identified a pattern) the fingerprint is different.

My suspect is that sometime avro4s returns me a slightly different schema. Maybe with some minor change... Because my case class never change and I assume that the avro fingerprint function is the same.
I have created an unit test where I check the fingerprint value and sometime it fails.

Do you have any idea?

**Comment by sksamuel** [comment]
Can you paste up the case class you're using ?

**Comment by davideicardi** [comment]
Thanks @sksamuel . Here the case class:

```
package com.mycompany

import com.sksamuel.avro4s.AvroName

case class ActivityEvent(
                                   uuid: String,
                                   @AvroName("eventName") eventName: event_name.Value,
                                   @AvroName("activityType") activityType: activity_type.Value,
                                   activityID: Int,
                                   activityRecordIndex: Int,
                                   utcTimestampBegin: String,
                                   utcTimestampEnd: Option[String] = None,
                                   isGpsOn: Option[Boolean] = None,
                                   batteryPercentage: Option[Int] = None,
                                   locations: Option[Seq[locations]] = None,
                                   accelerations: Option[Seq[accelerations]] = None,
                                   gyros: Option[Seq[gyros]] = None,
                                   magnetometers: Option[Seq[magnetometers]] = None,
                                   events: Option[Seq[events]] = None
                                 )

@AvroName("EventName") object event_name extends Enumeration {
  val ACTIVITY_START, ACTIVITY_STOP, ACTIVITY_RECORD = Value
}

@AvroName("ActivityType") object activity_type extends Enumeration {
  val IN_VEHICLE, ON_BICYCLE = Value
}
object event_type extends Enumeration {
  val STEP, PICKUP, GLANCE, WAKE_UP, TILT, SCREEN_UNLOCK = Value
}


case class locations(
                          utcTimestamp: String,
                          provider: String,
                          latitude: Float,
                          longitude: Float,
                          altitude: Option[Float] = None,
                          horizontalAccuracy: Option[Float] = None,
                          verticalAccuracy: Option[Float] = None,
                          speed: Option[Float] = None,
                          speedAccuracy: Option[Float] = None,
                          bearing: Option[Float] = None,
                          bearingAccuracy: Option[Long] = None
                        )

case class accelerations(
                         x: Float,
                         y: Float,
                         z: Float,
                         norm: Float,
                         accuracy: Int,
                         utcTimestamp: String
                       )

case class gyros(
                 x: Float,
                 y: Float,
                 z: Float,
                 accuracy: Int,
                 utcTimestamp: String
               )

case class magnetometers(
                         x: Float,
                         y: Float,
                         z: Float,
                         accuracy: Int,
                         utcTimestamp: String
                       )

case class events(
                       utcTimestamp: String,
                       @AvroName("event_type") eventType: event_type.Value,
                       magnitude: Option[Float] = None,
                       severity: Option[Int] = None,
                       accuracy: Option[Int] = None
                     )
```

**Comment by davideicardi** [comment]
I currently use avro4s version 2.0.2

**Comment by sksamuel** [comment]
I've added a test that generates 1000 schemas and takes the fingerprints of them. They all come out the same.

**Comment by davideicardi** [comment]
@sksamuel Can you just point me to the part of the code that generate the enum definition and the symbols? 
So that I can investigate further... thanks

**Comment by sksamuel** [comment]
https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L164-L219

**Comment by davideicardi** [comment]
Not yet, I have reproduced it in a small project, with just Avro4S and that case class. But I still don't understand the reason of this difference... I suspect some compilation issue. I will try to publish it somewhere so that you can have a look. Thanks for now.

**Comment by sksamuel** [comment]
This is probably fixed in 3.0.x snapshots as the macro code has been writtten.

**Comment by davideicardi** [comment]
Thanks! I will try it ASAP.

With 2.x version I still have the problem but it is very difficult to reproduce... Sometime our CI pipeline fails with this error, and the difference is on the symbols list.
I will update you.

**Comment by sksamuel** [comment]
Maybe related to #299

**Comment by davideicardi** [comment]
Unfortunately for now it is not probably possible for me to use new the avro4s version because it doesn't support any more Java annotations. Correct?
One of my team mate have tried to use it without success... We have some class annotated to support third party schemas.

**Comment by sksamuel** [comment]
What do you mean by not supporting Java annotations - do you mean it will break the schema generation? Because if so that's a bug.

**Comment by sksamuel** [comment]
There was a bug in magnolia around java annotations but that's been fixed. If you are still having issues please reopen this (or another) ticket.
