### ISSUE TITLE
Snapshots are not being released

### ISSUE THREAD

**Issue by sebastian-ziegler** [sksamuel/avro4s#551]
Hello!

I don't know if this is on purpose or what but checking at the snapshot_deploy step in [travis-ci in here](https://travis-ci.org/github/sksamuel/avro4s/jobs/726910512) it says the credentials for releasing snapshots are invalid, or the user is unauthorised. I was expecting to use a fix that was merged not so long ago and is not possible.

**Comment by sksamuel** [comment]
Thanks for pointing that out - fixed now, latest snapshot is up.

**Comment by sebastian-ziegler** [comment]
@sksamuel I think issue can be re-opened, it is still not working, and actually the snapshots for scala 2.13 are not there and according to [the logs it is still not working](https://travis-ci.org/github/sksamuel/avro4s/jobs/728708728#L2666)

**Comment by sksamuel** [comment]
That is trying to do a 4.1 snapshot.

**Comment by sksamuel** [comment]
The snapshots only ever deployed for 2.12 too. I  will switch them to 2.13 since 2.12 is eol.

**Comment by sebastian-ziegler** [comment]
Nice, thanks!

**Comment by sksamuel** [comment]
I've updated the build to use github actions and setup for 2.12 and 2.13
snapshots to be published.

The build number has reset so you will need to look inside the snapshots
repo for the latest version (which is be 4.1.0.25-SNAPSHOT right now)
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s/avro4s-core_2.13/
